### PR TITLE
Non-standard FDTD solver M4 and timestep dependent field interpolation scheme

### PR DESCRIPTION
**Pull request by yingchaolu**
# Non-standard FDTD solver M4 and timestep dependent field interpolation scheme

Implemented (1) non-standard FDTD solver `M4` and (2) timestep dependent field interpolation scheme (WT scheme) for suppressing numerical Cherenkov instability in ultrarelativistic drifting flow simulations. Both are according to [Y. Lu et al., J. Comput. Phys 413, 109388 (2020)](https://doi.org/10.1016/j.jcp.2020.109388).
The description of the features are added to the documentation in `namelist.rst` and `releases.rst`.
The initialization of timestep for `M4` and WT scheme is in `pyinit.py`.

## Non-standard FDTD solver ```M4```

The solver `M4` has fourth order accuracy for phase velocity, i.e. Taylor series of EM phase velocity is `v = 1 - O(k^4)` as `k -> 0`. 
To use `M4`, just turn set `maxwell_solver = "M4"`   in the namelist `Main`. 
If `M4` is used, then `full_B_exchange=true` in `Params.cpp`, which is similar to `Lehe` and `Bouchard`.
If `M4` is used, `SolverFactory.h` selects 
- `MF_Solver1D_M4` for `1DCartesian`
- `MF_Solver2D_M4` for `2DCartesian`
- `MF_Solver3D_M4` for `3DCartesian`

Created the following benchmarks:

- ```tst1d_22_em_dispersion_m4.py```
- ```tst2d_22_em_dispersion_m4.py```
- ```tst3d_22_em_dispersion_m4.py```

## WT scheme
To use WT scheme, just turn on `interpolation_WT = True`  in ```Main```. 
The `Main` variable `interpolation_WT` is defined in `Params.h`. 
If `interpolation_WT = True` is used, then `InterpolatorFactory.h` selects an `Interpolator` from following according to `interpolation_order`, `geometry`  and `vectorization`:

- `Interpolator1DWT2Order` for `interpolation_order = 2` and `geometry = "1DCartesian"`
- `Interpolator1DWT4Order` for `interpolation_order = 4` and `geometry = "1DCartesian"`
- `Interpolator2DWT2Order` for `interpolation_order = 2` and `geometry = "2DCartesian"` and `vectorization = False`
- `Interpolator2DWT4Order` for `interpolation_order = 4` and `geometry = "2DCartesian"` and `vectorization = False`
- `Interpolator2DWT2OrderV` for `interpolation_order = 2` and `geometry = "2DCartesian"` and `vectorization = True`
- `Interpolator2DWT4OrderV` for `interpolation_order = 4` and `geometry = "2DCartesian"` and `vectorization = True`
- `Interpolator3DWT2Order` for `interpolation_order = 2` and `geometry = "3DCartesian"` and `vectorization = False`
- `Interpolator3DWT4Order` for `interpolation_order = 4` and `geometry = "3DCartesian"` and `vectorization = False`
- `Interpolator3DWT2OrderV` for `interpolation_order = 2` and `geometry = "3DCartesian"` and `vectorization = True`
- `Interpolator3DWT4OrderV` for `interpolation_order = 4` and `geometry = "3DCartesian"` and `vectorization = True`

Created the following benchmarks:

- `tst1d_23_interpolation_wt2.py`
- `tst1d_23_interpolation_wt4.py`
- `tst2d_23_interpolation_wt2.py`
- `tst2d_23_interpolation_wt4.py`
- `tst2d_v_23_interpolation_wt2.py` (Vectorized version)
- `tst2d_v_23_interpolation_wt4.py` (Vectorized version)
- `tst3d_23_interpolation_wt2.py`
- `tst3d_23_interpolation_wt4.py`
- `tst3d_v_23_interpolation_wt2.py` (Vectorized version)
- `tst3d_v_23_interpolation_wt4.py` (Vectorized version)

### CODE REVIEW

**Comment by mccoys** [comment]
Thank you very much for this impressive work. It will take some time to review, and we will start after the holidays.

**Comment by xxirii** [comment]
Dear @yingchaolu,

I have started to review you pull request. It has passed our CI and I am now playing with the WT scheme to see how it affects some simulations I have. The M4 will be reviewed by one of my colleague. 

Concerning the namelist, we would like to propose something different. We would like to have an option called `interpolator` at the species level so that the user could select different interpolation schemes for different species. Therefore, the option would not be a boolean but a text field could be like that:
```
interpolator=`esirkepov`|`wt`
```

This is a change we can do on our side after the pull request.

**Comment by mccoys** [comment]
Is it a good idea to have the interpolation at the species level? Does it have a real justification?

**Comment by yingchaolu** [comment]
@xxirii Thank you for update. The WT scheme is for gathering fields to particles while "esirkepov" is for current deposition. Should the option be something like  ```interpolator=`esirkepov`|`wt` ```?

**Comment by xxirii** [comment]
Right, we should segregate the field interpolation and the current projection schemes.

So maybe something like 

field_interpolator = « direct » | « wt »

Do you think it is relevant to put this parameter at the species level?

**Comment by yingchaolu** [comment]
Per species level interpolation options might be useful for some applications.

Does it make more sense to have both field_interpolator and order for per species level?

**Comment by yingchaolu** [comment]
Sounds good.

**Comment by xxirii** [comment]
Hi Dr. Lu,

Your contribution is now merged in the master branch. I have used an intermediate branch to do that. I have just changed how it is managed in the namelist according to what we discussed before. So far, the choice of the interpolation scheme is still global not at the species level. We will see in the future if having this option at the species level is relevant.

Thank you again.

**Comment by yingchaolu** [comment]
> Hi Dr. Lu,
> 
> Your contribution is now merged in the master branch. I have used an intermediate branch to do that. I have just changed how it is managed in the namelist according to what we discussed before. So far, the choice of the interpolation scheme is still global not at the species level. We will see in the future if having this option at the species level is relevant.
> 
> Thank you again.

Dear @xxirii,

Great to know that WT and M4 have been merged in master. I think the per species interpolator option might be relevant to the situations where a relativistic beam is drifting in a non-relativistic background, since WT is only useful for relativistic drift speed.

Another suggestion, if one wants to make the code more readable. Some attributes and methods in WT interpolator are same as the momentum-conserving interpolator. Does it make sense to inherit from the momentum-conserving interpolator classes? I was trying to implement WT by inheriting some methods in the standard interpolator, but not sure if it is same to change those `override final` statements.

**Comment by xxirii** [comment]
For the per species I will keep in mind your argument.

In you case, inheritance from the momentum-conserving interpolator is necessary only if you want to inherit one of the methods not rewrite all of them. But this is not a big problem at the end. I think what you did is good and readable. One day we will have to make some cleaning in these old functions (interpolator but also projector and more).

**Pull request merged**
